version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
      - "9229:9229"  # For Node.js debugging
    environment:
      - NODE_ENV=development
      - CHROME_BIN=/usr/bin/chromium
      - DISPLAY=:99
      - DEBUG=*  # Enable debug logging
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./screenshots:/app/screenshots
    command: npm run dev  # Use development mode with hot-reloading
    restart: unless-stopped 