services:
  mcp-webdriverio:
    build:
      context: .
      target: production
    container_name: mcp-webdriverio-server
    volumes:
      - ./mcp-config.json:/app/mcp-config.json
      - ./uploads:/app/uploads
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/chromium
      - CHROME_PATH=/usr/lib/chromium/
    # For development, use this override:
    # command: npm run dev
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    restart: unless-stopped
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment if you need to expose a port
    # ports:
    #   - "4444:4444"
    # Add any additional environment variables here
    # environment:
    #   - WDIO_LOG_LEVEL=info
    #   - WDIO_MAX_INSTANCES=5 